/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cartera/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cartera_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cartera/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cartera_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CRMFila: {
            readonly id: number;
            /** Format: date */
            fecha_contacto?: string | null;
            /** Format: date */
            fecha_compromiso?: string | null;
            /** Format: date */
            fecha_pago?: string | null;
            estado?: (components["schemas"]["CRMFilaEstadoEnum"] | components["schemas"]["NullEnum"]) | null;
            pago?: (components["schemas"]["PagoEnum"] | components["schemas"]["NullEnum"]) | null;
            situacion?: (components["schemas"]["SituacionEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        /**
         * @description * `comprometido` - Comprometido
         *     * `sin_compromiso` - Sin compromiso
         *     * `pagado` - Pagado
         * @enum {string}
         */
        CRMFilaEstadoEnum: "comprometido" | "sin_compromiso" | "pagado";
        CarteraDetail: {
            readonly credito: components["schemas"]["CreditoResumen"];
            readonly crm: components["schemas"]["CRMFila"] | null;
            readonly cuotas: components["schemas"]["Cuota"][];
        };
        CarteraList: {
            readonly id: number;
            rut: string;
            cliente: string;
            /** Format: date */
            readonly fecha_contacto: string | null;
            /** Format: date */
            readonly fecha_compromiso: string | null;
            /** Format: date */
            readonly fecha_pago: string | null;
            readonly estado: (components["schemas"]["CRMFilaEstadoEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly pago: (components["schemas"]["PagoEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly situacion: (components["schemas"]["SituacionEnum"] | components["schemas"]["NullEnum"]) | null;
            cuotas: number;
            monto: number;
        };
        CreditoResumen: {
            id: number;
            rut: string;
            cliente: string;
        };
        Cuota: {
            readonly id: number;
            estado: components["schemas"]["CuotaEstadoEnum"];
            /** Format: date */
            fecha: string;
            monto: number;
        };
        /**
         * @description * `vencida` - Vencida
         *     * `vigente` - Vigente
         * @enum {string}
         */
        CuotaEstadoEnum: "vencida" | "vigente";
        /** @enum {unknown} */
        NullEnum: null;
        /**
         * @description * `total` - Total
         *     * `parcial` - Parcial
         * @enum {string}
         */
        PagoEnum: "total" | "parcial";
        /**
         * @description * `pendiente` - Pendiente
         *     * `validado` - Validado
         * @enum {string}
         */
        SituacionEnum: "pendiente" | "validado";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cartera_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarteraList"][];
                };
            };
        };
    };
    cartera_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this credito. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarteraDetail"];
                };
            };
        };
    };
}
