# Generated by Django 6.0.7 on 2026-07-22 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_deudor', models.CharField()),
            ],
            options={
                'db_table': 'credito',
            },
        ),
        migrations.CreateModel(
            name='CRMFila',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credito_id', models.IntegerField()),
                ('fecha_contacto', models.DateField(null=True)),
                ('fecha_compromiso', models.DateField(null=True)),
                ('fecha_pago', models.DateField(null=True)),
                ('estado', models.CharField(choices=[('comprometido', 'Comprometido'), ('sin_compromiso', 'Sin compromiso'), ('pagado', 'Pagado')], default='sin_compromiso', max_length=20)),
                ('pago', models.CharField(choices=[('total', 'Total'), ('parcial', 'Parcial')], max_length=20, null=True)),
                ('situacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado')], max_length=20, null=True)),
                ('cuotas', models.IntegerField()),
                ('monto', models.IntegerField()),
            ],
            options={
                'db_table': 'crm_fila',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('credito_id', models.ForeignKey(db_column='credito_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.credito')),
            ],
            options={
                'db_table': 'cuota',
            },
        ),
    ]
