# Generated by Django 6.0.7 on 2026-07-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmfila',
            name='credito_id',
        ),
    ]
