# Generated by Django 6.0.7 on 2026-07-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crmfila_credito_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfila',
            name='credito_id',
            field=models.ForeignKey(db_column='credito_id', on_delete=django.db.models.deletion.CASCADE, related_name='crm_fila', to='core.credito'),
        ),
    ]
