# Generated by Django 6.0.7 on 2026-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_crmfila_credito_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfila',
            name='estado',
            field=models.CharField(choices=[('comprometido', 'Comprometido'), ('sin_compromiso', 'Sin compromiso'), ('pagado', 'Pagado')], default='sin_compromiso', max_length=20, null=True),
        ),
    ]
