# Generated by Django 6.0.7 on 2026-07-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_crmfila_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmfila',
            name='cuotas',
        ),
        migrations.RemoveField(
            model_name='crmfila',
            name='monto',
        ),
    ]
