# Generated by Django 6.0.7 on 2026-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_crmfila_cuotas_remove_crmfila_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='estado',
            field=models.CharField(blank=True, choices=[('vencida', 'Vencida'), ('vigente', 'Vigente')], max_length=20, null=True),
        ),
    ]
