# Generated by Django 6.0.7 on 2026-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cuota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('vencida', 'Vencida'), ('vigente', 'Vigente')], max_length=20),
        ),
    ]
