# Generated by Django 6.0.7 on 2026-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cuota_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='nombre_deudor',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='credito',
            name='rut_deudor',
            field=models.CharField(max_length=20),
        ),
    ]
