# Generated by Django 6.0.7 on 2026-07-22 19:52

import re
import unicodedata

from django.db import migrations, models


def correo_desde_nombre(nombre, credito_id):
    nombre_normalizado = unicodedata.normalize("NFKD", nombre or "")
    nombre_normalizado = "".join(
        caracter
        for caracter in nombre_normalizado
        if not unicodedata.combining(caracter)
    ).lower()
    nombre_normalizado = re.sub(r"[^a-z0-9]+", ".", nombre_normalizado).strip(".")
    identificador = nombre_normalizado or f"deudor{credito_id}"
    return f"{identificador}@gmail.com"


def llenar_correos_deudores(apps, schema_editor):
    Credito = apps.get_model("core", "Credito")
    for credito in Credito.objects.all().iterator():
        credito.correo_deudor = correo_desde_nombre(
            credito.nombre_deudor,
            credito.id,
        )
        credito.save(update_fields=["correo_deudor"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_credito_nombre_deudor_alter_credito_rut_deudor'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='correo_deudor',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.RunPython(llenar_correos_deudores, migrations.RunPython.noop),
    ]
