# Generated by Django 6.0.7 on 2026-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_credito_correo_deudor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('request_text', models.CharField(default='')),
                ('request_hash', models.CharField(max_length=64)),
                ('response_text', models.CharField()),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_thoughts', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'request_cache',
                'constraints': [models.UniqueConstraint(fields=('model', 'request_hash'), name='uq_request_cache_model_hash')],
            },
        ),
    ]
