# Generated by Django 6.0.7 on 2026-07-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_requestcache'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credito',
            table='db_credito',
        ),
        migrations.AlterModelTable(
            name='crmfila',
            table='db_crm_fila',
        ),
        migrations.AlterModelTable(
            name='cuota',
            table='db_cuota',
        ),
        migrations.AlterModelTable(
            name='requestcache',
            table='db_request_cache',
        ),
    ]
