# Generated by Django 6.0.7 on 2026-07-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_crmfila_canal_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmfila',
            name='monto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='crm_fila_id',
            field=models.ForeignKey(blank=True, db_column='crm_fila_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas', to='core.crmfila'),
        ),
    ]
