# Generated by Django 6.0.7 on 2026-07-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_crmfila_monto_cuota_crm_fila_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_path', models.CharField(max_length=255)),
                ('monto_total', models.IntegerField()),
                ('fecha_pago', models.DateField(null=True)),
                ('cuenta_destino', models.CharField(max_length=50, null=True)),
                ('cuentas_distintas', models.BooleanField(default=False)),
                ('cantidad_transferencias', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('crm_fila_id', models.ForeignKey(db_column='crm_fila_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.crmfila')),
            ],
            options={
                'db_table': 'db_pago',
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_imputado', models.IntegerField()),
                ('cuota_id', models.ForeignKey(db_column='cuota_id', on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='core.cuota')),
                ('pago_id', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='core.pago')),
            ],
            options={
                'db_table': 'db_pago_cuota',
                'constraints': [models.UniqueConstraint(fields=('pago_id', 'cuota_id'), name='uq_pago_cuota')],
            },
        ),
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(null=True)),
                ('cuenta_destino', models.CharField(max_length=50, null=True)),
                ('banco', models.CharField(max_length=100, null=True)),
                ('n_operacion', models.CharField(max_length=50, null=True)),
                ('pago_id', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.pago')),
            ],
            options={
                'db_table': 'db_pago_transferencia',
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('pago_id', 'orden'), name='uq_pago_transferencia_orden')],
            },
        ),
    ]
