# Generated by Django 6.0.7 on 2026-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_ceco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_saf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('pago_total', 'Pago total'), ('put_cuotas', 'PUT en cuotas')], max_length=20, null=True),
        ),
    ]
