# Generated by Django 6.0.7 on 2026-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pago_monto_ceco_pago_monto_saf_pago_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfila',
            name='situacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado al mandante'), ('validado', 'Validado')], max_length=20, null=True),
        ),
    ]
