# Generated by Django 6.0.7 on 2026-08-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_crmfila_situacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='rut_transfiere',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
